export const templates = {
	template: [{ id: 0, title: 'SZABLON', icon: require('../assets/images/szablon.png') }],
	default: [
		{ id: 0, title: 'SZABLON', icon: require('../assets/images/szablon.png') },
		{ id: 1, title: '1.OTOCZENIE ZEWNĘTRZNE', icon: require('../assets/images/zew.png') },
		{ id: 2, title: '2.PARKING DLA OZN', icon: require('../assets/images/parking.jpg') },
		{ id: 3, title: '3.STREFA WEJŚCIA', icon: require('../assets/images/strefaWej.jpg') },
		{ id: 4, title: '4.SCHODY ZEWNĘTRZNE', icon: require('../assets/images/outdoor_stairs.jpg') },
		{ id: 5, title: '5.POCHYLNIE', icon: require('../assets/images/ramp.jpg') },
		{ id: 6, title: '6.DOMOFON', icon: require('../assets/images/domofon.jpg') },
		{ id: 7, title: '7.RECEPCJA', icon: require('../assets/images/reception.jpg') },
		{ id: 8, title: '8.KORYTARZE', icon: require('../assets/images/corridors.jpg') },
		{ id: 9, title: '9.KOMUNIKACJA PIONOWA', icon: require('../assets/images/stairs.jpg') },
		{ id: 10, title: '10.DZWIGI OSOBOWE PLATFORMY', icon: require('../assets/images/elevator.jpg') },
		{ id: 11, title: '11.WC', icon: require('../assets/images/wc.jpg') },
		{ id: 12, title: '12.POKOJE RODZICA Z DZIECKIEM', icon: require('../assets/images/parentChildren.jpg') },
		{ id: 13, title: '13.INNE POMIESZCZENIA', icon: require('../assets/images/otherRooms.jpg') },
		{ id: 14, title: '14.OCHRONA PRZECIWPOŻAROWA', icon: require('../assets/images/fireproof.jpg') },
		{ id: 15, title: '15.INFORMACJE', icon: require('../assets/images/information.jpg') },
		{ id: 16, title: '16.MATERIAŁY WYKOŃCZENIOWE', icon: require('../assets/images/materialywyk.jpg') },
		{ id: 17, title: 'KWESTIONARIUSZ GUS', icon: require('../assets/images/qa.png') },
	],
	klatki: [
		{ id: 0, title: 'SZABLON', icon: require('../assets/images/szablon.png') },
		{ id: 1, title: '1.OTOCZENIE ZEWNĘTRZNE', icon: require('../assets/images/zew.png') },
		{ id: 2, title: '2.PARKING DLA OZN', icon: require('../assets/images/parking.jpg') },
		{ id: 3, title: '3.STREFA WEJŚCIA', icon: require('../assets/images/strefaWej.jpg') },
		{ id: 4, title: '4.SCHODY ZEWNĘTRZNE', icon: require('../assets/images/outdoor_stairs.jpg') },
		{ id: 5, title: '5.POCHYLNIE', icon: require('../assets/images/ramp.jpg') },
		{ id: 6, title: '6.DOMOFON', icon: require('../assets/images/domofon.jpg') },
		{ id: 7, title: '7.KOMUNIKACJA PIONOWA', icon: require('../assets/images/stairs.jpg') },
		{ id: 8, title: '8.DZWIGI OSOBOWE PLATFORMY', icon: require('../assets/images/elevator.jpg') },
		{ id: 9, title: 'KWESTIONARIUSZ GUS', icon: require('../assets/images/information.jpg') },
	],
	knn: [
		{ id: 0, title: 'SZABLON', icon: require('../assets/images/szablon.png') },
		{ id: 1, title: '1.STREFA WEJŚCIA', icon: require('../assets/images/outdoor_stairs.jpg') },
		{ id: 2, title: '2.ORIENTACJA W BUDYNKU I PRZEKAZ INFORMACJI', icon: require('../assets/images/ramp.jpg') },
		// =========ZMIANA=========
		{ id: 3, title: '3.KOMUNIKACJA POZIOMA', icon: require('../assets/images/domofon.jpg') },
		{ id: 4, title: '4.KOMUNIKACJA PIONOWA', icon: require('../assets/images/stairs.jpg') },
		{ id: 5, title: '5.STANOWISKA POSTOJOWE', icon: require('../assets/images/elevator.jpg') },
		{ id: 6, title: '6.POMIESZCZENIA HIGIENICZNO-SANITARNE', icon: require('../assets/images/stairs.jpg') },
		{ id: 7, title: '7.STANOWISKO OBSŁUGI KLIENTA', icon: require('../assets/images/elevator.jpg') },
	],
}
